spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
#    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/infinitypo
    username: infinitypo
    password: infinitypo
    driver-class-name: org.postgresql.Driver
server:
  port: 8083
  servlet:
    context-path: /